### PR TITLE
Feat: use eask package manager

### PR DESCRIPTION
**Pull request by joshbax189**
Adds [Eask](https://emacs-eask.github.io/Getting-Started/Introduction/) and uses it for github actions.

Why use Eask:
- allows installing packages in CI
  can add optional dependencies only for test, e.g. `el-mock`, `nvm`
- similar interface to npm, 
  e.g. Eask file = package.json, `eask install`, `eask exec`, local packages installed to .eask dir
- built in commands for linting and testing
- available as a docker container or an [action](https://emacs-eask.github.io/Continuous-Integration/GitHub-Actions/)
- can be installed using npm

The main reason I'm suggesting this is to install `el-mock` and `company` for testing completions. But the other reasons make Eask worthwhile in any case. For example 14f5524 adds a CI job that will fail if nvm.el removes any functions that js-comint depends on, or changes their args. 798d5dc gives an example of using `el-mock` to test existing features. Using the existing scripts to do either of these would be fairly awkward.

### CODE REVIEW

**Comment by redguardtoo** [comment]
Could you do some rebase and resolve conflicts on this branch?

**Comment by joshbax189** [comment]
Sweet as, all done!

**Comment by redguardtoo** [comment]
Thanks

**Comment by jian-lin** [comment]
I created https://github.com/redguardtoo/js-comint/pull/40 to exclude test files from MELPA.

**Comment by redguardtoo** [comment]
sure. thanks

**Pull request merged**
